### ISSUE TITLE
Instructions to install

### ISSUE THREAD

**Issue by 603000** [theljwhite/pulseBPM-BPM-Detector#1]
Hi, could you provide brief isntructions on how to install your app?

**Comment by theljwhite** [comment]
Yes, no problem. I'm away from from my keyboard until later this evening, but once I'm back I'll provide instructions in here & also update the readme.

**Comment by theljwhite** [comment]
You should be able to clone the repo from Github, and in the project root directory, run "npm install" and it will install all of the necessary dependencies including React, etc. For the Spotify portion to work you will likely need to set up your own account and get an API key with Spotify and replace it,  somewhere here: https://developer.spotify.com/documentation/web-api/ ... once I'm back at my PC I'll try to provide further help when I can take a closer look at it.

**Comment by theljwhite** [comment]
Once you've installed the dependencies you should be able to just run "npm start" to launch the project on localhost.

**Comment by 603000** [comment]
Thank you very much! Could you give a bit more detailed explanation about Spotify API - where to place the key and what is the shortest way to obtain it? (tried to figure out myself reading docs on Spotify developer corner - looks like it is not as straightforward as it looks like)

**Comment by theljwhite** [comment]
No you are correct, it's not as straightforward as it could be and it seems like they have changed some things in their UI since I last used it, haha. You will want to create an account here. `https://developer.spotify.com/dashboard/login` 

Then, once you have an account, at the dashboard, click "Create an App" `https://developer.spotify.com/dashboard/applications`

Once you click into your app from the dashboard, a "Client Id"  should be visible at the top left with a button to un-hide your "Client Secret". These will allow you to fetch an authorization bearer token from Spotify from the project. All that you should need to do is replace the "CLIENT_ID" and "CLIENT_SECRET" variables at the top of src/Components/BPMDetectMain.tsx (lines 12 and 13)

One of the best ways to secure variables like these from the front-end are to store the values in a .env file. In the root directory of the project, create a file simply called ".env" 

Afterwards, set up your variables in the .env file like this:

`REACT_APP_CLIENT_ID = insert client id here`
`REACT_APP_CLIENT_SECRET = insert client secret here `
You do not have to put the numbers in single or double quotes, just leave them as is. 

Then, back in src/Components/BPMDetectMain.tsx, the CLIENT_ID and CLIENT_SECRET variables should be correct since using "process.env.REACT_APP_CLIENT_ID", etc, is fetching the values from the .env file. Alternatively, if you're not worried about security, you can simply pass in CLIENT ID and CLIENT SECRET without using a .env file. Like so:

`const CLIENT_ID: string = "000000000000000" `

If you have any other issues feel free to let me know and I'll get back to you later this evening. Thanks for pointing it out that I need to provide some instructions in the README file, haha.

**Comment by 603000** [comment]
Thanks a lot for the explanation - worked like a charm!
Do you know if it is possible to install your app on some hosting which supports node js apps? I tried but with no success, unfortunately. Probably, did something incorrectly.

**Comment by theljwhite** [comment]
Through what methodology are you attempting to apply hosting? You will likely have to run "npm run build" in the root directory in order to serve the content. Let me know and I may be able to provide assistance, haha.

**Comment by 603000** [comment]
I copy everything in the directory and follow these steps https://www.namecheap.com/support/knowledgebase/article.aspx/10047/2182/how-to-work-with-nodejs-app/ and nothing works)
Probably, I should use another name for Application startup file? I tried putting nothing in this field, then tried app.js and app.tsx - same result.
Only see when starting the app:
"It works!
NodeJS 10.24.1"

**Comment by theljwhite** [comment]
Not sure, will take a look in the morning when I’m back at my PC. I will say though, I’ve used Namecheap before, and with a CRA (Create React App) such as this, I have served an app before by going into File Manager in Namecheap’s cPanel, and under public/html folder, pasting in the minified build files. That should work. Essentially, it’s just running “npm run build” and then pasting in/uploading the contents of the “build” folder that it creates under “public/html”. I believe that’s the correct directory. Will check in the morning.

**Comment by 603000** [comment]
Again your advice helped a lot! Thank you very much!

**Comment by theljwhite** [comment]
No problem, glad to help. If you need anything further feel free to open another issue. :-)
